version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025" # Port SMTP
      - "8025:8025" # Interface Web
###< symfony/mailer ###
